### ISSUE TITLE
How to use LinGoose with LocalAI?

### ISSUE THREAD

**Issue by typomedia** [henomis/lingoose#110]
Hi! Is it possible to use LinGoose with [LocalAI](https://github.com/go-skynet/LocalAI) which has a OpenAI compatible API?

If so, cloud you provide a simple example? Since last week LocalAI has `api-key` support.

https://github.com/go-skynet/LocalAI/pull/877

**Comment by henomis** [comment]
You can use a custom [go-openai](https://github.com/sashabaranov/go-openai) client.

```go
customClient := goopenai.DefaultConfig("your api key")
custom.BaseURL = "http://localhost:8080"
```

then use LinGoose openai llm `WithClient(client *goopenai.Client)`

```go
llmOpenAI := openai.NewCompletion().WithClient(customClient)
```

Let me know if this works

**Comment by henomis** [comment]
v0.0.10 adds a localai example [here](https://github.com/henomis/lingoose/tree/main/examples/llm/openai/localai)
