### ISSUE TITLE
Build issue with index package (using Go 1.21)

### ISSUE THREAD

**Issue by flo8** [henomis/lingoose#113]
Hi! Thank you for this library, very excited to give it a try. When trying to build your quickstart, I run into these issues on go build (Go 1.21).

```
./main.go:18:8: undefined: index.NewSimpleVectorIndex
./main.go:19:27: undefined: index.NewSimpleVectorIndex
./main.go:19:127: undefined: index.WithTopK
```

All other packages seem to be correctly installed. Only "index" is preventing the build. Any idea what could be wrong here?

**Comment by henomis** [comment]
Fixed in: https://github.com/henomis/lingoose/pull/117
