### ISSUE TITLE
SimpleVectorIndex.load() is easy to be called more than once

### ISSUE THREAD

**Issue by FlyingDuck** [henomis/lingoose#120]
[index/simpleVectorIndex](https://github.com/henomis/lingoose/blob/main/index/simpleVectorIndex/simpleVectorIndex.go)

```golang
func (s *Index) IsEmpty() (bool, error) {
	...      
	err := s.load()
	...
}

func (s *Index) SimilaritySearch(ctx context.Context, query string, opts ...option.Option) (index.SearchResponses, error) {
	...
	err := s.load()
	...
}
```

The invocation of the `load()` function is very subtle, which easily leads to cases of repeated calls. Such as in the [example](https://github.com/henomis/lingoose/blob/main/examples/embeddings/simpleVector/main.go). 

We'd better make sure it's loaded only once.

**Comment by henomis** [comment]
Ok, added a task on the issue https://github.com/henomis/lingoose/issues/116

**Comment by henomis** [comment]
Fixed in https://github.com/henomis/lingoose/pull/123
