### ISSUE TITLE
Support WithHTTPClient() method in llm/openai like what's already done in llm/huggingface

### ISSUE THREAD

**Issue by hsluoyz** [henomis/lingoose#125]
See: https://github.com/search?q=repo%3Ahenomis%2Flingoose%20WithHTTPClient&type=code

**Comment by henomis** [comment]
In openai you have [`WithClient()`](https://github.com/henomis/lingoose/blob/main/llm/openai/openai.go#L122)

**Comment by hsluoyz** [comment]
Thanks for the answer!
