### ISSUE TITLE
Can vectordb increase support for memory instead of files?

### ISSUE THREAD

**Issue by polin-x** [henomis/lingoose#140]
Can vectordb increase support for memory instead of files?

**Comment by henomis** [comment]
Hi @polin-x I'm not sure to understand your request. Do you want an in-memory vector storage database?

**Comment by polin-x** [comment]
> Hi @polin-x I'm not sure to understand your request. Do you want an in-memory vector storage database?

yes

**Comment by henomis** [comment]
jsondb now is on memory by default, while using `WithPersist( )` the db will be stored in a json file.
