### ISSUE TITLE
Implement method for Vector Databases to delete collection/payloads

### ISSUE THREAD

**Issue by Vanclief** [henomis/lingoose#151]
**Is your feature request related to a problem? Please describe.**
Sometimes you do want to remove a collection/payload from a vector database, these methods are exposed by vector/databases APIs.

**Describe the solution you'd like**
Add a method to the index interface to allow for deletion of documents

**Comment by henomis** [comment]
Are these methods acceptable?

```go
func (i *Index) Drop(ctx context.Context) error 
func (i *Index) Delete(ctx context.Context, ids []string) error
```

**Comment by Vanclief** [comment]
Sorry, are you pointing out they already exist and I am missing them or proposing an interface for them?

If its the later I think they make sense. Let me know if I can help.

**Comment by henomis** [comment]
These methods have been implemented here https://github.com/henomis/lingoose/pull/158
