### ISSUE TITLE
Possible to use with a local LLM?

### ISSUE THREAD

**Issue by chrisbward** [henomis/lingoose#152]
As titled, would prefer to use a local LLM instead of OpenAI's GPT. I arrived here via this tutorial/introduction to RAG;

https://simonevellei.com/blog/posts/leveraging-go-and-redis-for-efficient-retrieval-augmented-generation/

**Comment by henomis** [comment]
I suggest to use [localAI](https://localai.io) and use a custom LLM. Then connect LinGoose to LocalAI using a custom openai client (`WithClient( )`) with local endpoint

**Comment by airtonix** [comment]
@henomis Can you comment on why localAI and not [Ollama](https://ollama.ai/)?

**Comment by henomis** [comment]
@airtonix I will check this project and the possibility of integrating it into Lingoose. Thanks for the suggestion.

**Comment by henomis** [comment]
Ollama will be supported in the next lingoose version.
