### ISSUE TITLE
support gpt-4-vision-preview

### ISSUE THREAD

**Issue by BabySid** [henomis/lingoose#161]
hi @henomis To be honest, I really like this project. In the world of Golang, it is indeed a very impressive project that has helped us solve many problems, such as memory, vector queries……
I have encountered a problem now

**Is your feature request related to a problem? Please describe.**
the ```Chat(ctx context.Context, prompt *chat.Chat)``` API don't support image input, even though I extended ```Prompt``` interface, and I found it didn't work. 

By analyzing the code, I discovered that the issue lies in the implementation of the Chat api(https://github.com/henomis/lingoose/blob/main/llm/openai/openai.go#L301). In the function buildMessages(), the user's  message is being uniformly formatted as a string(https://github.com/henomis/lingoose/blob/main/llm/openai/openai.go#L446). If the user's data type is an json array, it is also being formatted as a string. As a result, when GPT responds, it produces gibberish instead of the intended output.

Here is a specific demonstration of the issue:
The correct json:
```json
{
    "model": "gpt-4-vision-preview",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "What’s in this image?"
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://.../some.jpg"
            }
          }
        ]
      }
    ]
  }
```

The json generated by lingoose
```json
{
    "model": "gpt-4-vision-preview",
    "messages": [
      {
        "role": "user",
        "content": "[{\"type\": \"text\",\"text\": \"What’s in this image?\" },{ \"type\": \"image_url\", \"image_url\": {\"url\": \"https://.../some.jpg\"}} ]"
      }
    ]
  }
```

**Describe the solution you'd like**
The corresponding data structures are already supported in the foundational library(https://github.com/sashabaranov/go-openai/blob/master/chat.go#L85), so an upgrade is required to support the corresponding data fields.

**Additional context**

**Comment by henomis** [comment]
Hi @BabySid , thank you for your feedback!
There is a **huge** PR on going that will introduce the concept of `Thread`. This will support multimodal content (such the one from openai). This means that `chat.Chat` become *legacy* and all the new features will be implemented over `Thread`. 

Here is how `Thread` can be used with `GPT4VisionPreview` and multimodal contents: [main.go](https://github.com/henomis/lingoose/blob/5bc2d82253a70772d9442c5fc864bfc7d790352a/examples/llm/openai/multimodal/main.go).

I'm writing the new documentation, and as soon I've finished I'll release the new version.

**Comment by BabySid** [comment]
Thank you very much for the response. This looks really great! Looking forward to the New Amazing Version.

**Comment by BabySid** [comment]
I have used version 0.1.0, it works. perfect work! thanks very much @henomis
