### ISSUE TITLE
Require Pointer Type

### ISSUE THREAD

**Issue by Lenstack** [henomis/lingoose#185]
https://github.com/henomis/lingoose/blob/7ea0cd0ffb053da68c07e1fc05b64fab9ba52adb/llm/openai/openai.go#L346
![Captura de pantalla 2024-03-21 165857](https://github.com/henomis/lingoose/assets/42081538/950a42a6-47f3-42b8-ae3d-54eee7a7a623)
![imagen](https://github.com/henomis/lingoose/assets/42081538/6d9f09cb-db1c-43cf-b551-de80ef28284c)

**Comment by Lenstack** [comment]
We could use 	Type: openai.AssistantToolTypeFunction, Function: &openai.FunctionDefinition{}

**Comment by henomis** [comment]
@Lenstack I don't understand your issue. Please check imports and be sure to alias lingoose's openai to avoid conflicts with the go openai package.

**Comment by Lenstack** [comment]
@henomis Internally, Lingosse uses "github.com/sashabaranov/go-openai". Therefore, in the implementation of getChatCompletionRequestTools, when using openai.FunctionDefinition{}, it requires to be called as &openai.FunctionDefinition{} because "FunctionDefinition" is a pointer.

**Comment by henomis** [comment]
@Lenstack Lingoose uses v1.19.2 of the go-openai package. In this version `FunctionDefinition` is not a pointer.
If it had been a pointer the code would give compiling errors. Your [PR](https://github.com/henomis/lingoose/pull/186) is broken, indeed.

**Comment by henomis** [comment]
As there's been no follow-up on the requested changes, I'm closing this issue.
