### ISSUE TITLE
No embedding found while querying qdrant

### ISSUE THREAD

**Issue by parikxxit** [henomis/lingoose#202]
**Describe the bug**
After creating new Qdrant Index while we perform the query to the qdrant db sometime we are not getting 

**To Reproduce**
1. Create a Qdrant Index used following command 

```
   opt  := qdrant.Options{CollectionName: collectionName}
   qdrantIndex := index.New(
		qdrant.New(opt).WithAPIKeyAndEdpoint(token, "http://localhost:6333"),
		embedder,
	)
	
```

2. Perform Query operation on qdrant 

`similarity, err := qdrantIndex.Query(context.Background(), "pizza", option.WithTopK(100), option.WithFilter(queryFilter))`

3. Got Panic from Qdrant

**Expected behavior**

Instead of throwing panic it should have thrown out the error

**Screenshots**

<img width="1159" alt="Screenshot 2024-05-25 at 12 18 19 AM" src="https://github.com/henomis/lingoose/assets/22438509/178645e0-dcbd-469a-ab21-bdb84958b3ad">
<img width="1159" alt="Screenshot 2024-05-25 at 12 39 07 AM" src="https://github.com/henomis/lingoose/assets/22438509/f037a512-de4b-48a5-896c-af0564b23903">

**Desktop (please complete the following information):**
 - OS: macOS 12.7.1 (21G920)
 - Browser NA
 - Version v0.1.2

**Additional context**
May be I am creating index incorrectly even tough we should return error over panicking the entire system

**Comment by henomis** [comment]
@parikxxit Please provide a full example, this will add more context. From your PR it looks like your `embedder` failed to produce embeddings, and accessing to `embeddings[0]` will cause panic. If so the problem is elsewhere.

**Comment by henomis** [comment]
no more information received
