### ISSUE TITLE
Parse embedding error, expected all numeric but string is prefixed with "embedding 0:

### ISSUE THREAD

**Issue by kbrisso** [henomis/lingoose#213]
**Describe the bug**
When using llama-embeddings.exe the embedding returns a string from the command out that is formatted like this "embedding 0:"  0.011059 -0.014784 -0.018492  0.020268 -0.027386  0.022915 " This part "embedding 0" is causing the issue.

**To Reproduce**
llama-embedding.exe -m mxbai-embed-large-v1-f16.gguf --pooling mean -p "Madam Speaker Madam Vice President our First Lady and Second Gentleman. Members of Congress and the Cabinet. Justices of the Supreme Court. My fellow Americans. Last year COVID-19 kept us apart. This year we are finally together again. Tonight we meet as Democrats Republicans and Independents. But most importantly as Americans. With a duty to one another to the American people to the Constitution. And with an u" >>log.text

**Expected behavior**
String with spaces with no alpha text, all text should numeric.

**Screenshots**
Posted issues in Discord.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by kbrisso** [comment]
I have a local branch with a fix in it. I can create a pull if needed.

**Comment by henomis** [comment]
Hi @kbrisso, I'm not sure this issue is related to Lingoose, the project doesn't have a tool called `llama-embeddings.exe`

**Comment by kbrisso** [comment]
> Hi @kbrisso, I'm not sure this issue is related to Lingoose, the project doesn't have a tool called `llama-embeddings.exe`

Here is the full code snippet. You call the llama.cpp embedder exe "llama-embedding.exe" with this method llamacppembedder.New().WithModel(......).WithLlamaCppPath(.......)  

![Screenshot 2024-09-07 115142](https://github.com/user-attachments/assets/0ae03295-a3c8-42ce-ab6a-ec30b2712e22)

This is how I fixed it in your llamaccp.go file in your project.

![Screenshot 2024-09-07 115716](https://github.com/user-attachments/assets/da735167-1a51-4874-8daf-fb41e6a08620)

**Comment by henomis** [comment]
Could you try without `--embd-output-format` and `--embd-separator`?

**Comment by kbrisso** [comment]
> Could you try without `--embd-output-format` and `--embd-separator`?

I tried all the settings and none of them worked. I spent all weekend on this. Your code expects a perfect string that can be converted to a slice. If you review the llama.cpp code you will see it returns the string like below

**"embedding 0:"** 0.011059 -0.014784 -0.018492 0.020268 -0.027386 0.022915

**Comment by kbrisso** [comment]
> Ok let's try the lingoose version `v0.2.1-alpha.2` with the hotfix for that and remove `--embd-output-format` and `--embd-separator` args.

Works great! Thanks!

**Comment by henomis** [comment]
fixed here: https://github.com/henomis/lingoose/issues/200
