### ISSUE TITLE
Shouldn't the package and types for Anthropic include the letter 'h'?

### ISSUE THREAD

**Issue by klauern** [henomis/lingoose#215]
**Describe the bug**

I am not sure if this is intentional or not, but shouldn't the Anthropic API's use `anthropic` instead of `antropic`?  There's a couple places that just seem like a spelling error, and I'm not sure if it's too late to correct or not.

* https://github.com/henomis/lingoose/tree/main/llm/antropic
* https://github.com/henomis/lingoose/blob/3930e2bdb0daf7e6f93cc71830627b81cdd0d11f/llm/antropic/antropic.go#L46

**Comment by henomis** [comment]
fixed here: https://github.com/henomis/lingoose/issues/200
